# Numpy

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([[11,1.2,13,14,15],[1,2,3,4,5]])
print(a)
print(b)

[1 2 3 4 5]
[[11.   1.2 13.  14.  15. ]
 [ 1.   2.   3.   4.   5. ]]


 ### checking np version

In [47]:
print(np.__version__)

1.26.4


# Basics/ndarray attributes

In [25]:
#dimension
b.ndim

2

In [26]:
#no of elements
b.size

10

In [27]:
#type
b.dtype

dtype('float64')

In [28]:
#size
b.itemsize

8

In [40]:
#shape
b.shape

(2, 5)

In [41]:
#total size
b.size*b.itemsize

80

# Creating arrays

In [31]:
#0-D array
x=np.array(30)
print(x)

30


In [32]:
#1-D array
y=np.array([1,2,3])
print(y)

[1 2 3]


In [33]:
#2-d array
z=np.array([[1,2],[3,4]])
print(z)

[[1 2]
 [3 4]]


In [39]:
#creating any dimensional array
d=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=5)
print(d)
d.ndim

[[[[[ 1  2  3  4  5]
    [ 6  7  8  9 10]]]]]


5

# Accessing elements / Indexing

In [42]:
s=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(s)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [44]:
s[1,5]

13

In [45]:
s[1,-1]

14

In [47]:
#entire column
s[:,2]

array([ 3, 10])

In [48]:
#entire row
s[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [49]:
s[0,2:5]

array([3, 4, 5])

In [50]:
s[0,2:7:2]

array([3, 5, 7])

In [52]:
s[1,1:-2:2]

array([ 9, 11])

In [55]:
#changing an element
s[1,5]=20
print(s)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [56]:
#changing specific column of elements
s[:,6]=[5,5]
print(s)

[[ 1  2  3  4  5  6  5]
 [ 8  9 10 11 12 20  5]]


In [57]:
s

array([[ 1,  2,  3,  4,  5,  6,  5],
       [ 8,  9, 10, 11, 12, 20,  5]])

# Initialising different types of arrays
zeros,ones,full,full_like

In [59]:
# Initialising with zeros--by default dtype is float
m=np.zeros(7)
m

array([0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [69]:
np.zeros([3,2],dtype="bool")

array([[False, False],
       [False, False],
       [False, False]])

In [72]:
g=np.ones([2,3])
g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
g.astype("int")

array([[1, 1, 1],
       [1, 1, 1]])

In [77]:
# By using full---by default int
#np array(shape,value,dtype)
np.full(3,2)

array([2, 2, 2])

In [78]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [85]:
np.full((2,3),5,dtype=float)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [95]:
np.full(g.shape,5)

array([[5, 5, 5],
       [5, 5, 5]])

In [96]:
# By using full_like
np.full_like(g,3)

array([[3., 3., 3.],
       [3., 3., 3.]])

# Random numbers
### randint()

In [6]:
#first import the random module
from numpy import random
#between range of values
x=random.randint(100,200)
print(x)
y=random.randint(50)
print(y)

154
32


In [11]:
random.randint(5,size=2)

array([2, 3])

### rand()

In [7]:
#generate ramdom float btw 0 to 1
random.rand()

0.42292934341670974

In [8]:
random.rand(3)

array([0.85633164, 0.20917143, 0.72483775])

In [12]:
random.rand(3,5)

array([[0.46232737, 0.94312902, 0.656892  , 0.68702157, 0.67043158],
       [0.07776179, 0.71827039, 0.06865114, 0.73318389, 0.15427649],
       [0.53000996, 0.90251419, 0.46977331, 0.5638798 , 0.5752872 ]])

### choice()

In [19]:
#generating random number from an array
g=random.choice([5,3,7])
print(g)

7


In [22]:
g=random.choice([5,7,3],size=(2,5))
print(g)

[[7 3 5 7 7]
 [7 3 3 5 3]]


In [26]:
#probability of occuring the particular random number
#probabilities should sum to 1
g=random.choice([5,3,7],p=[0.3,0.0,0.7],size=(3,3))
print(g)

[[7 5 7]
 [7 7 7]
 [7 7 5]]


## Random permutations
permutation means arrangement of elements

methods are : shuffle() and permutation()

In [43]:
#ramdom shuffling of an array---changes the original array
import numpy as np
arr=np.array([1,3,5,2,4,6])
a=random.shuffle(arr)
print(a)
print(arr)

None
[2 1 6 4 3 5]


In [45]:
#permutation -------- do not change the original array
arr=np.array([1,3,5,2,4,6])
a=random.permutation(arr)
print(a)
print(arr)

[2 4 6 5 1 3]
[1 3 5 2 4 6]


# Numpy Datatypes

strings , integer , float , boolean , complex

i-integer\
b-boolean\
u-unsigned integer\
f-float\
c-complex float\
m-timedelta\
M-datetime\
O-object\
S-string\
U-unicode string\
V-fixed chunk of memory for other type



In [48]:
a=np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int64


In [50]:
a=np.array([1,2,3,4,5],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [54]:
a=np.array([1,2,3,4,5],dtype='m')
print(a)
print(a.dtype)

[1 2 3 4 5]
timedelta64


## copy() vs view()

copy()---will not change the original array---owns data\
view()---will change the original array---does not own data

In [55]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=7
print(a)
print(x)

[7 2 3 4 5]
[1 2 3 4 5]


In [56]:
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=7
print(a)
print(x)

[7 2 3 4 5]
[7 2 3 4 5]


base()---checks if the array owns the data or not

In [59]:
a=np.array([1,2,3,4,5])
x=a.view()
y=a.copy()
print(a.base)
print(x.base)

None
[1 2 3 4 5]


# Some methods

### reshape()
we can use -1 as one of the dimension

In [62]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,1,-1)
print(b)

[[[1 2 3]]

 [[4 5 6]]]


### nditer()

In [65]:
a=np.array([1,2,3,4,5])
for x in np.nditer(a):
    print(x)

1
2
3
4
5


we can change datatype of elements while iterating by using\
op_dtypes

In [68]:
a=np.array([1,2,3,4,5])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


### enumerate()
displays elememts along with their sequence

In [69]:
a=np.array([1,2,3,4,5])
for x,i in np.ndenumerate(a):
    print(x,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


### arange()

In [19]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


### reshape()

In [24]:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
a=np.arange(1,13,2).reshape(3,2)
print(a)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


### repeat()

In [27]:
a=np.array([1,2,3])
r=np.repeat(a,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [31]:
a=np.array([[1,2,3],[4,5,6]])
r=np.repeat(a,3,axis=0) # repeating rows
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [30]:
a=np.array([[1,2,3],[4,5,6]])
r=np.repeat(a,3,axis=1) # repeating columns
print(r)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


# Joining arrays
we use concatenate() along with the axis\
If axis is not explicitly passed it is taken as 0\
we also use stack() function


In [73]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a=np.concatenate((a1,a2))
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [154]:
a1=np.array([[1,2],[3,4]])#the array should be homogeneous
a2=np.array([[6,7],[8,9]])
a=np.concatenate((a1,a2))
print(a)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [155]:
# concatenating with the axis
a1=np.array([[1,2],[3,4]])#the array should be homogeneous
a2=np.array([[6,7],[8,9]])
a=np.concatenate((a1,a2),axis=0)
print(a)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [79]:
# concatenating with the axis
a1=np.array([[1,2],[3,4]])#the array should be homogeneous
a2=np.array([[6,7],[8,9]])
a=np.concatenate((a1,a2),axis=1)
print(a)

[[1 2 6 7]
 [3 4 8 9]]


In [85]:
# using stack()

a1=np.array([1,2,3])
a2=np.array([6,7,8])
a=np.stack((a1,a2),axis=1)
print(a)

[[1 6]
 [2 7]
 [3 8]]


In [80]:
# using stack()

a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
a=np.stack((a1,a2),axis=0)
print(a)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [81]:
# using stack()

a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
a=np.stack((a1,a2),axis=1)
print(a)

[[[1 2]
  [6 7]]

 [[3 4]
  [8 9]]]


hstack()---stack along rows


In [88]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
a=np.hstack((a1,a2))
print(a)

[[1 2 6 7]
 [3 4 8 9]]


In [96]:
a1=np.array([1,2,3])
a2=np.array([6,7,8])
a=np.hstack((a1,a2))
print(a)

[1 2 3 6 7 8]


vstack()---stack along columns

In [90]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
a=np.vstack((a1,a2))
print(a)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [92]:
a1=np.array([1,2,3])
a2=np.array([6,7,8])
a=np.vstack((a1,a2))
print(a)

[[1 2 3]
 [6 7 8]]


dstack()---stack along height

In [93]:
a1=np.array([1,2,3])
a2=np.array([6,7,8])
a=np.dstack((a1,a2))
print(a)

[[[1 6]
  [2 7]
  [3 8]]]


In [94]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
a=np.dstack((a1,a2))
print(a)

[[[1 6]
  [2 7]]

 [[3 8]
  [4 9]]]


# Splitting arrays
It is the reverse operation of joining\
we use array_split()---theparameters are the array and the no of splits

splitting 1-D array

In [117]:
a=np.array([1,2,3,4,5,6])
np.array_split(a,3)
#print(a1)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [118]:
a=np.array([1,2,3,4,5,6])
a1=np.array_split(a,4)
print(a1)
a2=a1[1]
print(a1[0][1])
print(a2)

[array([1, 2]), array([3, 4]), array([5]), array([6])]
2
[3 4]


In [119]:
a=np.array([1,2,3,4,5,6,7])
np.array_split(a,3)
#print(a1)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]

split() can also be used as an alternative but it will result in error if there is no equal division

splitting 2-D array

In [156]:
#equal division
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
np.array_split(a,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [157]:
#unequal division
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
np.array_split(a,4)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

split along the row

In [127]:
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
np.array_split(a,4,axis=1)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]

In [132]:
#hsplit()---should be of equal division
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
np.hsplit(a,2)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [138]:
#vsplit()---should be of equal division
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
np.vsplit(a,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

# Searching arrays
Can find indexes\
we use where()\
searchsorted()---performs binary search in array---assumed to be used on sorted arrays

## where()

In [139]:
a=np.array([[1,2],[3,1],[5,6],[7,8],[2,10],[11,12]])
x=np.where(a==2)
print(x)

(array([0, 4]), array([1, 0]))


In [140]:
a=np.array([1,2,3,4,5,6,7])
x=np.where(a%2==1)
print(x)

(array([0, 2, 4, 6]),)


## searchsorted()

In [158]:
# to find the index where the particular element can be inserted
a=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(a,5.2)# 5.2 can be inserted at 5th index position
print(x)

5


In [160]:
a=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(a,5)
print(x)

4


In [161]:
a=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(a,5,side='right')
print(x)

5


In [163]:
# to search for multiple elements
a=np.array([1,2,3,4,5,6,7])
x=np.searchsorted(a,[5,2,7])
print(x)

[4 1 6]


# Sorting arrays

In [165]:
# returns a copy of array---original array is unchanged
a=np.array([3,2,0,1])
a1=np.sort(a)
print(a1)

[0 1 2 3]


In [166]:
a=np.array([3,2,0,1])
print(np.sort(a))

[0 1 2 3]


In [167]:
# sorting strings
a=np.array(['guava','pineapple','mango','grapes','orange'])
print(np.sort(a))

['grapes' 'guava' 'mango' 'orange' 'pineapple']


In [179]:
a=np.array([True,True,False,'Cat','cat'])
print(np.sort(a))

['Cat' 'False' 'True' 'True' 'cat']


Sorting 2-D array

In [178]:
a=np.array([[3,2,4],[5,0,1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


# Filtering the array

In [5]:
arr=np.array([1,2,3,4,5])
a=[True,True,False,False,True]
newarr=arr[a]
print(newarr)

[1 2 5]


In [8]:
arr=np.array([1,2,3,4,5,6,7])
fil_arr=[]
for i in arr:
    if i>=5:
        fil_arr.append(True)
    else:
        fil_arr.append(False)
newarr=arr[fil_arr]
print(newarr)

[5 6 7]


# Simple Arithmetic Operations 
add()\
subtract()\
multiply()\
divide()\
power()\
mod() or remainder()---returns remainder of values\
divmod()---returns both quotient and mod in two arrays\
absolute() or abs()---but absolute() is preferable


In [9]:
a=np.array([10,20,30,40,50])
a+2

array([12, 22, 32, 42, 52])

In [10]:
a-3

array([ 7, 17, 27, 37, 47])

In [11]:
a**2

array([ 100,  400,  900, 1600, 2500])

In [15]:
a%11 # returns remainder

array([10,  9,  8,  7,  6])

In [16]:
a//3  # returns quotient

array([ 3,  6, 10, 13, 16])

In [18]:
# divmod()---returns both remainder and quotient
a1=np.array([10,20,30,40,50,60])
a2=np.array([3,7,9,8,2,33])
new=np.divmod(a1,a2)
print(new)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [21]:
# absolute()
a=np.array([-2,-5,7,3],dtype='float')
n=np.absolute(a)
print(n)

[2. 5. 7. 3.]


# Rounding decimals
trunc() and fix()-----remove the decimals and return the float number closest to zero\
trunc()---truncation of fractional part\
fix()---more about fixing the value by moving towards zero


### trun() and fix()

In [23]:
# using trunc()
a=np.array([3.7,-3.7,2.5,-2.5,1.3,-1.3])
n=np.trunc(a)
print(n)

[ 3. -3.  2. -2.  1. -1.]


In [24]:
# using fix()
a=np.array([3.7,-3.7,2.5,-2.5,1.3,-1.3])
n=np.fix(a)
print(n)

[ 3. -3.  2. -2.  1. -1.]


### around()
round off to 1 decimal point

In [6]:
# round off to 2 decimal places
a=np.array([3.1666,-2.723,5.5])
n=np.around(a,2)
print(n)

[ 3.17 -2.72  5.5 ]


In [10]:
# rounf off to 3 decimal places
a=np.array([3.16665623,-2.726526,5.507724])
n=np.around(a,3)
print(n)

[ 3.167 -2.727  5.508]


### floor()
rounds off decimal to nearest lower integer

In [15]:
a=np.array([3.16665623,-2.426526,5.507724,2.2,2.7,2.0,0.2])
n=np.floor(a)
print(n)

[ 3. -3.  5.  2.  2.  2.  0.]


### ceil()
rounds off decimal to nearest upper integer

In [17]:
a=np.array([3.16665623,-2.426526,5.507724,2.2,2.7,2.0,0.2,-1.72,0.0,-1.23])
n=np.ceil(a)
print(n)

[ 4. -2.  6.  3.  3.  2.  1. -1.  0. -1.]


# Linear Algebra
## Matrix Operations

### dot()
product of two arrays

In [32]:
a=np.array([1,2,3])
b=np.array([5,6,7])
np.dot(a,b)

38

In [55]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,2]])
np.dot(a,b)

array([[19, 10],
       [43, 26]])

### inner product

In [35]:
a=np.array([1,2,3])
b=np.array([5,6,7])
np.inner(a,b)

38

In [40]:
a=np.array([[1,2],[3,4]])   #[[1*5+2*6  1*7+2*2]   [[5+12  7+4]
b=np.array([[5,6],[7,2]])   #[3*5+4*6  3*7+4*2]]   [15+24 21+8]]
np.inner(a,b)

array([[17, 11],
       [39, 29]])

### outer product

In [41]:
a=np.array([1,2,3])
b=np.array([5,6,7])
np.outer(a,b)

array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21]])

In [42]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,2]])
np.outer(a,b)

array([[ 5,  6,  7,  2],
       [10, 12, 14,  4],
       [15, 18, 21,  6],
       [20, 24, 28,  8]])

### determinant of matrix

In [47]:
# det() function from linalg module
a=np.array([[1,3],[5,7]])
b=np.array([[5,6],[7,2]])
result=np.linalg.det(a)
print(result)

-7.999999999999998


In [51]:
c=np.identity(3)
np.linalg.det(c)

1.0

### solve()
to solve system of linear equations\
--> works only for square matrix\
for a matrix with det=0 inv() function will raise LinAlgError exception

In [49]:
# define coefficient matrix A    
A=np.array([[2,4],[6,8]])                #2x+4y=5
# define the constant vector b           #6x+8y=6
b=np.array([5,6])
# solve the equations
result=np.linalg.solve(A,b)
print(result)

[-2.    2.25]


### inv()
--> to find inverse of square matrix\
--> for a matrix with det=0 inv() function will raise LinAlgError exception

In [50]:
a=np.array([[2,4],[6,8]])
result=np.linalg.inv(a)
print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]


### trace()
--> sum of diagonal elements of matrix

In [54]:
a=np.array([[6,3,5],[9,2,1],[7,8,4]])
print(a)
r=np.trace(a)
print(r)

[[6 3 5]
 [9 2 1]
 [7 8 4]]
12


### transpose()

In [59]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,2],[8,9]])
r1=np.transpose(a)
r2=np.transpose(b)
print(r1)
print(r2)

[[1 3]
 [2 4]]
[[5 7 8]
 [6 2 9]]


### svd()

In [64]:
a=np.array([[1,2,3],[4,5,6],[7,3,4]])
np.linalg.svd(a)

SVDResult(U=array([[-0.27696153, -0.44020445, -0.85411495],
       [-0.69295974, -0.52427824,  0.49491325],
       [-0.6656569 ,  0.72893921, -0.15983905]]), S=array([12.41571223,  3.27320231,  0.36910232]), Vh=array([[-0.62085837, -0.48452254, -0.61625709],
       [ 0.78371478, -0.40174189, -0.47370307],
       [ 0.01805647,  0.7770723 , -0.62915229]]))

### eigen values and eigen vectors

In [66]:
(values,vectors)=np.linalg.eig(a)
print(values)
print('\n')
print(vectors)

[11.45683654 -2.08483086  0.62799432]


[[-0.31195169 -0.51735194  0.09525004]
 [-0.74323266 -0.36387042 -0.83367823]
 [-0.59185417  0.77456135  0.5439743 ]]


In [67]:
np.linalg.norm(a)

12.84523257866513

## Mathematics

In [69]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[5,6,7]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [70]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [71]:
a%2

array([[1, 0, 1],
       [0, 1, 0]])

In [72]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [73]:
np.cos(b)

array([[-0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225]])

In [75]:
np.power(a,2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [79]:
np.exp(a) # e**number where e=2.71828

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [81]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [85]:
#matrix multiplication
a=np.array([[1,2],[4,5]])
b=np.array([[2,3],[5,6]])
a@b

array([[12, 15],
       [33, 42]])

In [87]:
np.matmul(a,b)

array([[12, 15],
       [33, 42]])

# Statistics
## min , max , sum , mean , median , std , var 

In [102]:
a=np.random.randint(2,11,size=(3,5))
print(a)

[[ 2 10  7 10  6]
 [ 8  8  5  9  6]
 [ 4  6  2  6  4]]


In [103]:
np.min(a)

2

In [105]:
np.min(a,axis=0) # columns

array([2, 6, 2, 6, 4])

In [106]:
np.min(a,axis=1) # rows

array([2, 5, 2])

In [107]:
np.max(a)

10

In [108]:
np.max(a,axis=0)

array([ 8, 10,  7, 10,  6])

In [109]:
np.max(a,axis=1)

array([10,  9,  6])

In [110]:
np.sum(a)

93

In [111]:
np.sum(a,axis=0)

array([14, 24, 14, 25, 16])

In [112]:
np.sum(a,axis=1)

array([35, 36, 22])

In [113]:
np.mean(a)

6.2

In [114]:
np.mean(a,axis=0)

array([4.66666667, 8.        , 4.66666667, 8.33333333, 5.33333333])

In [115]:
np.mean(a,axis=1)

array([7. , 7.2, 4.4])

In [116]:
np.median(a)

6.0

In [117]:
np.median(a,axis=0)

array([4., 8., 5., 9., 6.])

In [118]:
np.median(a,axis=1)

array([7., 8., 4.])

In [120]:
np.std(a)

2.4549270186029295

In [121]:
np.std(a,axis=0)

array([2.49443826, 1.63299316, 2.05480467, 1.69967317, 0.94280904])

In [122]:
np.std(a,axis=1)

array([2.96647939, 1.46969385, 1.49666295])

In [123]:
np.var(a)

6.026666666666667

In [124]:
np.var(a,axis=0)

array([6.22222222, 2.66666667, 4.22222222, 2.88888889, 0.88888889])

In [125]:
np.var(a,axis=1)

array([8.8 , 2.16, 2.24])

# Loading data from file

In [130]:
f=np.genfromtxt("/home/apiiit123/Videos/ml_learning_algorithms_krishnaik/python_libraries/sample.txt",delimiter=',',dtype='int')
f

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

# Advanced Indexing and Boolean Masking

In [131]:
filedata=f
filedata>17

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [134]:
filedata[filedata>17]

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

### we can index with a list in numpy

In [135]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [137]:
np.any(filedata>17,axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
np.all(filedata>8,axis=0)

array([False, False, False, False, False, False, False, False,  True,
        True])

### special indexing

In [147]:
a=np.ones((5,5),dtype='int')
print(a)
ins=np.zeros((3,3),dtype='int')
ins[1,1]=9
print(ins)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [158]:
a[1:4:,1:4:]=ins
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])